### ISSUE TITLE
Trees menu doesn't appear after install on Blender 4.2.2 LTS MacOS 15

### ISSUE THREAD

**Issue by calmasacow** [gregzaal/Matalogue#15]
Trees menu doesn't appear after install on Blender 4.2.2 LTS MacOS 15

Says it is installed and running but no Trees tab in N menu

**Comment by gregzaal** [comment]
I can't reproduce this issue, it's working fine on my end. If it's still broken for you, please include more details like a console log and/or steps to reproduce from factory defaults.
