### ISSUE TITLE
Only Compositing and Group Tree is shown

### ISSUE THREAD

**Issue by benjamindahl** [gregzaal/Matalogue#8]
I'm a bit clueless about how to use matalogue. Either something is not showing up in my Window or I didn't get how to use the material node system right.

When I hit Trees in the Node window toolbar. I just got two trees. One for Compositing and One for Groups but none for Lamp Nodes or Material Nodes.

Is there some kind of tutorial?

![bildschirmfoto 2016-06-02 um 10 19 44](https://cloud.githubusercontent.com/assets/2698024/15738634/7bc50d2c-28ac-11e6-808a-890029a6ff08.png)

Cheers 

Benny

**Comment by benjamindahl** [comment]
Ok, I got it. I just had to switch the render engine from blender render to cycles. Thanks.

**Comment by gregzaal** [comment]
Yep, only Cycles is supported.
